### PR TITLE
updated README.md

### PR DESCRIPTION
**Pull request by siryoung97**
readme 작성해봤는데 부족한 점이나 수정이 필요한 부분이 있으면 지적 부탁드립니다.

### CODE REVIEW

**Comment by ahastudio** [comment]
Write in English: documents, commit logs and pull requests.

See this guide: https://github.com/agis/git-style-guide

Add a newline to EOF. If you see on GitHub, you can see that the file needs a newline.

**Comment by siryoung97** [comment]
changed  readme.md language to english

**Comment by ahastudio** [comment]
If you want to manage to-dos, check this article: https://blog.github.com/2014-04-28-task-lists-in-all-markdown-documents/

**Comment by ahastudio** [comment]
Modify commit log in this order:
1. Make the summary text to be capitalized and be in present tense.
2. Write description: what and why did you do.
3. Apply this also to pull request.

**Comment by Artifriends** [comment]
Please write for beginners.
Everyone should be able to install easily.

**Pull request closed without merging**
